server:
  port: 9999
spring:
  application:
    name: proxy-service
  cloud:
    gateway:
      routes:
      - id: course-service
        uri: http://localhost:8001/
        predicates:
        - Path=/course/**
      - id: teacher-service
        uri: http://localhost:8002/
        predicates:
        - Path=/teacher/**
        
        
       